services:
  frontend:
    image: wellingtonollv/frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - fullstack-assessment-network

  backend:
    image: wellingtonollv/backend:latest
    container_name: backend
    restart: on-failure
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - database
    networks:
      - fullstack-assessment-network

  database:
    image: postgres:latest
    container_name: database
    restart: on-failure
    env_file:
      - ./backend/.env.production
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack-assessment-network

networks:
  fullstack-assessment-network:
    driver: bridge

volumes:
  postgres_data:
